name: CI Test

on:
  push:
    branches:
      - main  # Listen for pushes to the main branch
  pull_request:
    branches:
      - main  # Listen for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code to the runner

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up the Python environment
      with:
        python-version: '3.10'  # Specify the Python version, e.g., '3.8', '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Run tests
      run: pytest tests/  # Run the test code
