coverage:
  round: up
  range: 0..10
  precision: 5
  status:
    project:
      default:
        target: auto
        threshold: 1%
    # NEW: Add a status check specifically for the 'unit' flag
  unit_tests_coverage:
    target: auto
    threshold: 1%
    flags:
      - unit

codecov:
  strict_yaml_branch: default
  max_report_age: off

# NEW: Define the flags and the paths they cover
flags:
  unit:
    paths:
      - package/src/
    carryforward: true # Useful if you run different tests on different commits
