environments:
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive via Docker.
  jfm:
    kind: uv-venv
    path: requirements.txt
    prefix: .venv
pipeline:
  stages:
    generate-figs:
      kind: python-script
      script_path: dev/python/analysis/make_fig.py
      environment: jfm
      inputs:
        - package/src/
      outputs:
        - pubs/JFM/figs/sample_plot.png
    compile-overleaf:
      kind: latex
      target_path: pubs/JFM/FLMguide.tex
      environment: tex
      inputs:
        - pubs/JFM/FLMguide.tex
        - pubs/JFM/figs/
        - pubs/JFM/JFM-FLM_Au.cls
        - pubs/JFM/jfm.bib
        - pubs/JFM/jfm.bst
        - pubs/JFM/lineno-FLM.sty
        - pubs/JFM/zotero-meem-refs.bib
      outputs:
        - pubs/JFM/FLMguide.pdf
publications:
  - path: pubs/JFM/FLMguide.pdf
    title: Numerics of the matched eigenfunction method for computing 
      wave forces on concentric bodies
    description:
    kind: journal-article
    stage: build-pubs-jfm
    overleaf:
      project_id: 685318d5f36d3cd58760e69b
      wdir: pubs/JFM
      sync_paths:
        - FLMguide.tex
        - figs
        - JFM-FLM_Au.cls
        - jfm.bib
        - jfm.bst
        - lineno-FLM.sty
        - zotero-meem-refs.bib
        - FLMguide.pdf
      push_paths:
        - figs
      last_sync_commit: 4644454bbe08107978c58c490eb04ad111a38196
owner: symbiotic-engineering
name: openflash
title: OpenFLASH
description:
git_repo_url: https://github.com/symbiotic-engineering/OpenFLASH
