environments:
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive via Docker.
  openflash-on-branch:
    path: analysis/environment-branch.yml
    kind: conda
  openflash-on-main:
    path: analysis/environment-main.yml
    kind: conda
pipeline:
  stages:
    generate-figs:
      kind: python-script
      script_path: analysis/make_fig.py
      environment: openflash-on-main
      inputs:
        - package/src/
      outputs:
        - pubs/JFM/figs/sample_plot.png
    validate-w-capy:
      kind: jupyter-notebook
      notebook_path: analysis/validation_with_capytaine_plots.ipynb
      environment: openflash-on-branch
    low-m0-figs:
      kind: jupyter-notebook
      notebook_path: analysis/low_m0_plots.ipynb
      environment: openflash-on-branch
      inputs:
        - package/src/
        - dev/python/limiting-cases/low_m0.py
        - sea-lab-utils
      outputs:
        - pubs/JFM/figs/MEEM-Low-Freq.pdf
    slant-figs:
      kind: jupyter-notebook
      notebook_path: analysis/slant_data_plots.ipynb
      environment: openflash-on-branch
      inputs:
        - analysis/data/slants.pkl
        - sea-lab-utils
      outputs:
        - pubs/JFM/figs/MEEM-CPT-Slant-Freq.pdf
        - pubs/JFM/figs/MEEM-CPT-Slant-Subdivisions.pdf
    timing-figs:
      kind: jupyter-notebook
      notebook_path: analysis/timing_plots.ipynb
      environment: openflash-on-branch
      inputs:
        - analysis/data/timing.pkl
        - sea-lab-utils
      outputs:
        - pubs/JFM/figs/MEEM-Comp-Distribution.pdf
        - pubs/JFM/figs/MEEM-CPT-Speed-Comparison.pdf
    compile-overleaf:
      kind: latex
      target_path: pubs/JFM/FLMguide.tex
      environment: tex
      inputs:
        - pubs/JFM/FLMguide.tex
        - pubs/JFM/figs/
        - pubs/JFM/JFM-FLM_Au.cls
        - pubs/JFM/jfm.bib
        - pubs/JFM/jfm.bst
        - pubs/JFM/lineno-FLM.sty
        - pubs/JFM/zotero-meem-refs.bib
      outputs:
        - pubs/JFM/FLMguide.pdf
publications:
  - path: pubs/JFM/FLMguide.pdf
    title: Numerics of the matched eigenfunction method for computing 
      wave forces on concentric bodies
    description:
    kind: journal-article
    stage: build-pubs-jfm
owner: symbiotic-engineering
name: openflash
title: OpenFLASH
description:
git_repo_url: https://github.com/symbiotic-engineering/OpenFLASH
overleaf_sync:
  pubs/JFM:
    url: https://www.overleaf.com/project/685318d5f36d3cd58760e69b
    sync_paths:
      - FLMguide.tex
      - figs
      - JFM-FLM_Au.cls
      - jfm.bib
      - jfm.bst
      - lineno-FLM.sty
      - zotero-meem-refs.bib
      - FLMguide.pdf
